import { Upgrade, HistoricalEvent } from './types';

export const INITIAL_STATE = {
  money: 0,
  cloth: 0,
  population: 10,
  workers: 1, // Start with 1 worker (family)
  year: 1750,
  pollution: 0,
  productionRate: 0,
  clickPower: 1,
  isWeaving: false,
  weaveProgress: 0,
  steamEngineActive: false,
  needsYarn: false,
  needsMaintenance: false,
  yarnTimer: 0,
  maintenanceTimer: 0,
  wageTimer: 0,
  gameWon: false,
};

export const UPGRADES: Upgrade[] = [
  {
    id: 'flying-shuttle',
    name: 'Schietspoel',
    description: 'Door de schietspoel wordt het mogelijk om sneller stoffen te weven.',
    consequence: 'De schietspoel (uitgevonden door John Kay in Lancashire) zorgde ervoor dat wevers veel sneller konden werken. Het directe gevolg in Engeland was de "Yarn Famine": er was een groot tekort aan garen omdat de spinsters het tempo niet konden bijhouden.',
    imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.industriemuseum.be%2Ffiles%2Fattachments%2F.5848%2Fw1440q85_schietspoel.jpg&f=1&nofb=1&ipt=131641debae10065c40c781421d6c3a99ba0bc06e8fecb7c947a41e54849b605',
    cost: 50,
    purchased: false,
    type: 'invention',
    yearRequirement: 1733,
    effect: (s) => ({ clickPower: s.clickPower + 1 }),
  },
  {
    id: 'spinning-jenny',
    name: 'Spinning Jenny',
    description: 'Deze machine kan meerdere draden tegelijk spinnen, waardoor de productie wordt verhoogd.',
    consequence: 'James Hargreaves uit Stanhill, Engeland, bedacht de Spinning Jenny. Waar een spinster eerst één draad spon, kon ze er nu 8 tot 80 tegelijk maken. Huisnijverheid bereikte een piek, maar de prijzen van garen kelderden.',
    imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fc8.alamy.com%2Fcomp%2FG37W9W%2Fhargreaves-spinning-jenny-james-hargreaves-in-1767-invented-this-jenny-G37W9W.jpg&f=1&nofb=1&ipt=cec543474aa61f98c6677846feebd5e2c1037345e0e24903a6a75148e9cebb02',
    cost: 150,
    purchased: false,
    triggerEvent: 'event-jenny',
    type: 'invention',
    yearRequirement: 1764,
    effect: (s) => ({ clickPower: s.clickPower * 2, productionRate: s.productionRate + 1 }),
  },
  {
    id: 'water-frame',
    name: 'Waterframe',
    description: 'Machines worden niet meer met de hand aangedreven, maar door waterkracht.',
    consequence: 'Richard Arkwright ontwikkelde het Waterframe. Deze machine was te groot en zwaar voor in een huisje en moest worden aangedreven door een waterrad. Gevolg: De productie verplaatste zich van de huiskamer naar de eerste fabrieken langs snelstromende rivieren.',
    imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.historycrunch.com%2Fuploads%2F4%2F1%2F1%2F6%2F41169839%2Fpublished%2Fwater-frame.jpg%3F1565331279&f=1&nofb=1&ipt=e5503ae3e256d37a17be0c52a41b1b9f6ddd6ff765499ff7c0934be7dbdd7b17',
    cost: 500,
    purchased: false,
    type: 'building',
    yearRequirement: 1769,
    effect: (s) => ({ productionRate: 60, workers: 10 }),
  },
  {
    id: 'steam-engine',
    name: 'Stoommachine (Watt)',
    description: 'De stoommachine drijft de machines in de fabrieken aan, waardoor zij niet meer afhankelijk zijn van waterkracht.',
    consequence: 'James Watt verbeterde de stoommachine in 1776 zodat deze een draaiende beweging kon maken. Gevolg: Fabrieken hoefden niet meer aan een rivier te staan, maar verhuisden naar steden en plekken met steenkool. Dit veroorzaakte enorme urbanisatie en luchtvervuiling.',
    imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.zaans-industrieel-erfgoed.nl%2Fimages_5%2Fjames-watt-01.jpg&f=1&nofb=1&ipt=165523f0e59c959a37081caf1a334fb589e1e7b4ff3830d0d1eb45dfdd788045',
    cost: 2000,
    purchased: false,
    triggerEvent: 'event-steam',
    type: 'invention',
    yearRequirement: 1776,
    effect: (s) => ({ pollution: s.pollution + 10, workers: 20, productionRate: 180 }), 
  },
  {
    id: 'factory-system',
    name: 'Fabriekssysteem',
    description: 'Om grote machines werden fabrieken heengebouwd, waardoor er massaproductie ontstaat.',
    consequence: 'Het fabriekssysteem werd de norm in Engeland. Ambachtslieden werden fabrieksarbeiders die leefden op het ritme van de stoomfluit. Gevolg: Ontstaan van een arbeidersklasse (proletariaat) en slechte leefomstandigheden in de steden.',
    imageUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.britannica.com%2F58%2F223158-050-A61FA1C8%2Fspinning-room-in-Shadwell-Rope-Works.jpg&f=1&nofb=1&ipt=d5fef81ebb4f28fd9530c0d445f60e1eed18d9105f632b4d9f90224db8e2734d',
    cost: 5000,
    purchased: false,
    type: 'policy',
    yearRequirement: 1780,
    effect: (s) => ({ productionRate: 500, population: s.population * 2, pollution: s.pollution + 20, workers: 100 }),
  },
];

export const EVENTS: HistoricalEvent[] = [
  {
    id: 'start',
    title: 'Huisnijverheid (1750)',
    message: 'Je bent een wever in 1750 op het Engelse platteland. Het hele gezin werkt mee in de "Putting-out system". Het werk is zwaar en traag. Probeer genoeg te verdienen om te investeren in de nieuwe uitvindingen die eraan komen.',
    year: 1750,
    triggered: false,
  },
  {
    id: 'event-jenny',
    title: 'De Spinning Jenny (1764)',
    message: 'In Stanhill, Lancashire, heeft James Hargreaves een apparaat bedacht waarmee je 8 draden tegelijk kunt spinnen. De spinsters zijn bang hun baan te verliezen, maar de productie schiet omhoog!',
    year: 1764,
    triggered: false,
  },
  {
    id: 'event-steam',
    title: 'Het Stoom Tijdperk (1776)',
    message: 'James Watt heeft de stoommachine efficiënter gemaakt. Nu kunnen we fabrieken bouwen waar we maar willen, zolang er maar steenkool is. De lucht wordt grauw, maar de winst is enorm.',
    year: 1776,
    triggered: false,
  },
];